(function () {
    const API = (window.MAYCHILLS_API_URL || 'https://mayschillsbackend.onrender.com') + '/api';
    const money = value => `₦${Number(value || 0).toLocaleString()}`;
    const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));
    const date = value => value ? new Date(value).toLocaleDateString('en-NG', { day: 'numeric', month: 'short', year: 'numeric' }) : '—';
    const request = (path, options = {}) => fetch(API + path, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${sessionStorage.getItem('maychills_admin_token') || ''}` } }).then(response => { if (!response.ok) throw new Error('Request failed'); return response.json(); });
    let data;

    function card(label, value, note = '') { return `<div class="stat"><small style="display:block;color:var(--muted);font-weight:400">${label}</small><strong style="font-size:20px">${value}</strong>${note ? `<small style="display:block;color:var(--muted);font-weight:400">${note}</small>` : ''}</div>`; }
    function addPages() {
        const nav = document.querySelector('.nav'); const app = document.getElementById('app');
        if (!nav || !app || document.getElementById('crm-page')) return;
        nav.insertAdjacentHTML('afterbegin', '<button class="btn secondary" data-crm-page="crm-page">Dashboard</button><button class="btn secondary" data-crm-page="customers-page">Customers</button>');
        app.insertAdjacentHTML('beforeend', '<section id="crm-page" class="page"><div class="panel"><div class="toolbar"><div><h2 style="margin:0">Business dashboard</h2><p class="notice">A simple view of what sold, who bought, and what is changing.</p></div><div><select id="crm-range" class="input" style="width:auto"><option value="7">Last 7 days</option><option value="30" selected>Last 30 days</option><option value="month">This month</option></select> <button class="btn secondary" id="crm-refresh">Refresh</button></div></div><div id="crm-summary" class="stats" style="margin-top:18px"></div><div id="crm-insights" style="margin-top:20px"></div><div id="crm-products" style="margin-top:20px"></div></div></section><section id="customers-page" class="page"><div class="panel"><div class="toolbar"><div><h2 style="margin:0">Customers</h2><p class="notice">Profiles are built automatically from paid orders.</p></div><select id="crm-segment" class="input" style="width:auto"><option value="">All customers</option><option>New customer</option><option>Returning customer</option><option>Regular customer</option><option>Frequent customer</option><option>High-value customer</option><option>At-risk customer</option><option>Inactive customer</option></select></div><div id="crm-customers" style="margin-top:18px"></div></section>');
        nav.querySelectorAll('[data-crm-page]').forEach(button => button.addEventListener('click', () => { nav.querySelectorAll('button').forEach(item => item.classList.toggle('active', item === button)); document.querySelectorAll('.page').forEach(page => page.classList.toggle('active', page.id === button.dataset.crmPage)); if (button.dataset.crmPage === 'crm-page') load(); }));
        document.getElementById('crm-refresh').addEventListener('click', load); document.getElementById('crm-range').addEventListener('change', load); document.getElementById('crm-segment').addEventListener('change', renderCustomers);
    }
    function renderProducts() {
        const products = [...(data.products || [])]; const order = document.getElementById('crm-sort')?.value || 'units'; products.sort((a, b) => order === 'revenue' ? b.revenue - a.revenue : order === 'trend' ? (b.trend || -999) - (a.trend || -999) : order === 'decline' ? (a.trend || 999) - (b.trend || 999) : b.units - a.units);
        document.getElementById('crm-products').innerHTML = `<div class="toolbar"><h3 style="margin:0">Menu performance</h3><select id="crm-sort" class="input" style="width:auto"><option value="units">Most sold</option><option value="revenue">Highest revenue</option><option value="trend">Fastest growth</option><option value="decline">Biggest decline</option></select></div><div style="overflow:auto"><table style="width:100%;border-collapse:collapse;margin-top:12px"><thead><tr style="text-align:left;color:var(--muted)"><th>Product</th><th>Units</th><th>Revenue</th><th>Orders</th><th>Trend</th></tr></thead><tbody>${products.map(product => `<tr data-product="${esc(product.key)}" style="border-top:1px solid var(--line);cursor:pointer"><td style="padding:12px 4px;font-weight:700">${esc(product.name)}</td><td>${product.units}</td><td>${money(product.revenue)}</td><td>${product.orders}</td><td style="color:${product.trend >= 0 ? 'var(--g)' : 'var(--red)'}">${product.trend == null ? 'New' : `${product.trend >= 0 ? '+' : ''}${product.trend}%`}</td></tr>`).join('')}</tbody></table></div><div id="crm-product-detail" class="notice" style="margin-top:15px"></div>`;
        document.getElementById('crm-sort').addEventListener('change', renderProducts); document.querySelectorAll('[data-product]').forEach(row => row.addEventListener('click', () => { const product = products.find(item => item.key === row.dataset.product); document.getElementById('crm-product-detail').innerHTML = product ? `<div class="panel" style="margin-top:12px"><h3 style="margin-top:0">${esc(product.name)}</h3><p>${product.units} units sold, generating ${money(product.revenue)} across ${product.orders} orders.</p><p>Average quantity/order: ${product.averageQuantity.toFixed(1)} · Best days: ${esc(product.bestDays.join(', ') || 'Not enough data')} · Commonly bought with: ${esc(product.alongside.map(item => item.name).join(', ') || 'Not enough data')}</p><p>Frequent customers: ${esc(product.customers.join(', ') || 'Not enough data')}</p></div>` : ''; }));
    }
    function renderCustomers() {
        const filter = document.getElementById('crm-segment')?.value || ''; const customers = (data.customers || []).filter(customer => !filter || customer.segment === filter);
        document.getElementById('crm-customers').innerHTML = customers.length ? customers.map(customer => `<details class="item" style="margin-bottom:10px"><summary style="cursor:pointer"><strong>${esc(customer.name)}</strong> · ${money(customer.spent)} · ${esc(customer.segment)}<span class="notice" style="float:right">${customer.orders} order${customer.orders === 1 ? '' : 's'}</span></summary><div class="item-meta" style="margin-top:12px">${esc(customer.phone || customer.email || 'No contact saved')} · First order ${date(customer.firstOrder)} · Last order ${date(customer.lastOrder)} · Favourite: ${esc(customer.favoriteProduct)}</div><div style="margin-top:12px">${customer.history.map(order => `<div style="padding:8px 0;border-top:1px solid var(--line)">${date(order.date)} · ${money(order.total)} · ${esc(order.status)} · ${order.items.map(item => `${item.quantity}× ${esc(item.name)}`).join(', ')}</div>`).join('')}</div><textarea class="input crm-notes" data-customer="${esc(customer.key)}" rows="2" placeholder="Customer notes">${esc(customer.notes)}</textarea><button class="btn secondary crm-save-note" data-customer="${esc(customer.key)}">Save note</button></details>`).join('') : '<p class="notice">No customers match this filter yet.</p>';
        document.querySelectorAll('.crm-save-note').forEach(button => button.addEventListener('click', async () => { const notes = document.querySelector(`.crm-notes[data-customer="${CSS.escape(button.dataset.customer)}"]`).value; await request('/admin/customers/' + encodeURIComponent(button.dataset.customer) + '/notes', { method: 'PATCH', body: JSON.stringify({ notes }) }); button.textContent = 'Saved'; setTimeout(() => button.textContent = 'Save note', 1200); }));
    }
    function render() {
        const summary = data.summary || {}; const change = summary.salesChange == null ? 'No comparison yet' : `${summary.salesChange >= 0 ? '+' : ''}${summary.salesChange}% vs previous 30 days`;
        document.getElementById('crm-summary').innerHTML = card('Sales · last 30 days', money(summary.sales), change) + card('Orders', summary.orders) + card('Average order', money(summary.averageOrderValue)) + card('Items sold', summary.units) + card('Identified customers', summary.uniqueCustomers) + card('New customers', summary.newCustomers) + card('Returning customers', summary.returningCustomers);
        document.getElementById('crm-insights').innerHTML = data.insights?.length ? `<h3>What to pay attention to</h3><div class="alert">${data.insights.map(esc).join('<br>')}</div>` : '<p class="notice">More paid orders are needed before reliable insights can be shown.</p>';
        renderProducts(); renderCustomers();
    }
    async function load() { if (!sessionStorage.getItem('maychills_admin_token')) return; addPages(); try { const range = document.getElementById('crm-range')?.value || '30'; const end = new Date(); let start = new Date(end); if (range === 'month') start = new Date(end.getFullYear(), end.getMonth(), 1); else start.setDate(start.getDate() - Number(range)); data = await request(`/admin/analytics?from=${start.toISOString().slice(0, 10)}&to=${end.toISOString().slice(0, 10)}`); render(); } catch (error) { const target = document.getElementById('crm-summary'); if (target) target.innerHTML = '<p class="notice" style="color:var(--red)">Analytics are unavailable. Check the database connection.</p>'; } }
    const watcher = setInterval(() => { if (document.getElementById('app') && !document.getElementById('app').classList.contains('hidden')) { clearInterval(watcher); load(); } }, 250);
})();
