(function () {
    const API = (window.MAYCHILLS_API_URL || 'https://mayschillsbackend.onrender.com') + '/api';
    const money = value => `₦${Number(value || 0).toLocaleString()}`;
    const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));
    const date = value => value ? new Date(value).toLocaleDateString('en-NG', { day: 'numeric', month: 'short', year: 'numeric' }) : '—';
    const request = (path, options = {}) => fetch(API + path, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${sessionStorage.getItem('maychills_admin_token') || ''}` } }).then(response => { if (!response.ok) throw new Error('Request failed'); return response.json(); });
    let data;

    function card(label, value, note = '') { return `<div class="stat"><small style="display:block;color:var(--muted);font-weight:400">${label}</small><strong style="font-size:20px">${value}</strong>${note ? `<small style="display:block;color:var(--muted);font-weight:400">${note}</small>` : ''}</div>`; }
    function addPages() {
        if (!document.getElementById('dashboard-styles')) { const styles = document.createElement('style'); styles.id = 'dashboard-styles'; styles.textContent = '.dashboard-panel{padding:30px}.dashboard-toolbar{display:flex;justify-content:space-between;align-items:flex-start;gap:28px;padding-bottom:24px;border-bottom:1px solid var(--line)}.dashboard-controls{display:grid;grid-template-columns:minmax(150px,190px) auto;gap:8px 10px;align-items:end;min-width:270px}.dashboard-controls .notice{grid-column:1/-1;margin:0}.dashboard-controls .input{width:100%;margin:0}.dashboard-controls .btn{height:42px}.dashboard-stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:14px;margin-top:26px}.dashboard-stats .stat{min-height:86px;padding:15px 16px;display:flex;flex-direction:column;justify-content:space-between}.dashboard-section{margin-top:32px;padding-top:4px}.dashboard-section h3{margin:0 0 14px;font-size:18px}.dashboard-section .alert{padding:16px 18px;line-height:1.7;border-radius:12px}.dashboard-section table{background:#fff;border:1px solid var(--line);border-radius:12px;overflow:hidden}.dashboard-section th{padding:13px 10px;background:#f7faf7}.dashboard-section td{padding:14px 10px}.customer-grid,.order-status-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.customer-card{margin:0}.customer-card summary{display:flex;justify-content:space-between;gap:12px;list-style:none}.customer-facts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:18px}.customer-facts div{display:flex;flex-direction:column;gap:4px;padding:10px;border-radius:10px;background:#f7faf7}.customer-facts b{font-size:11px;color:var(--muted);text-transform:uppercase}.customer-facts span,.customer-history span{overflow-wrap:anywhere;font-size:13px}.customer-history{display:grid;gap:10px;margin-top:18px}.customer-history div{display:grid;gap:3px;padding:10px 0;border-top:1px solid var(--line)}.order-status-section{margin-top:26px}.order-status-section h3{margin:0 0 12px}.order-status-grid{align-items:start}.order-status-grid .order-card{margin:0}.order-card .input{max-width:240px}@media(max-width:700px){.dashboard-panel{padding:20px}.dashboard-toolbar{display:block}.dashboard-controls{margin-top:20px;min-width:0;grid-template-columns:1fr auto}.dashboard-stats{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.dashboard-section{margin-top:24px}.dashboard-section table{font-size:13px}.customer-grid,.order-status-grid{grid-template-columns:1fr}.customer-facts{grid-template-columns:1fr}}'; document.head.appendChild(styles); }
        const nav = document.querySelector('.nav'); const app = document.getElementById('app');
        const normalizeOrderStatuses = () => document.querySelectorAll('[data-order-status]').forEach(select => { if (select.dataset.statusNormalized) return; const current = select.value; select.innerHTML = '<option value="received">Received</option><option value="preparing">Preparing</option><option value="ready">Ready for pickup</option><option value="in_transit">In transit</option><option value="delivered">Delivered</option><option value="cancelled">Cancelled</option><option value="picked_up">Picked up</option>'; select.value = current === 'out_for_delivery' ? 'in_transit' : current; select.dataset.statusNormalized = 'true'; });
        const orders = document.getElementById('orders'); if (orders) new MutationObserver(normalizeOrderStatuses).observe(orders, { childList:true, subtree:true });
        if (!nav || !app || document.getElementById('crm-page')) return;
        nav.insertAdjacentHTML('afterbegin', '<button class="btn secondary" data-crm-page="crm-page">Dashboard</button><button class="btn secondary" data-crm-page="customers-page">Customers</button>');
        app.insertAdjacentHTML('beforeend', '<section id="crm-page" class="page"><div class="panel dashboard-panel"><div class="dashboard-toolbar"><div><h2 style="margin:0">Business dashboard</h2><p class="notice">Today\'s sales, orders, customers, and menu performance.</p></div><div class="dashboard-controls"><label class="notice" for="crm-range">Reporting period</label><select id="crm-range" class="input"><option value="today" selected>Today</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="month">This month</option></select><button class="btn secondary" id="crm-refresh">Refresh</button></div></div><div id="crm-summary" class="stats dashboard-stats"></div><div id="crm-insights" class="dashboard-section"></div><div id="crm-products" class="dashboard-section"></div></div></section><section id="customers-page" class="page"><div class="panel"><div class="toolbar"><div><h2 style="margin:0">Customers</h2><p class="notice">Profiles are built automatically from paid orders.</p></div><select id="crm-segment" class="input" style="width:auto"><option value="">All customers</option><option>New customer</option><option>Returning customer</option><option>Regular customer</option><option>Frequent customer</option><option>High-value customer</option><option>At-risk customer</option><option>Inactive customer</option></select></div><div id="crm-customers" style="margin-top:18px"></div></section>');
        nav.querySelectorAll('[data-crm-page]').forEach(button => button.addEventListener('click', () => { nav.querySelectorAll('button').forEach(item => item.classList.toggle('active', item === button)); document.querySelectorAll('.page').forEach(page => page.classList.toggle('active', page.id === button.dataset.crmPage)); if (button.dataset.crmPage === 'crm-page') load(); }));
        document.getElementById('crm-refresh').addEventListener('click', load); document.getElementById('crm-range').addEventListener('change', load); document.getElementById('crm-segment').addEventListener('change', renderCustomers);
    }
    function renderProducts() {
        const products = [...(data.products || [])]; const order = document.getElementById('crm-sort')?.value || 'units'; products.sort((a, b) => order === 'revenue' ? b.revenue - a.revenue : order === 'trend' ? (b.trend || -999) - (a.trend || -999) : order === 'decline' ? (a.trend || 999) - (b.trend || 999) : b.units - a.units);
        document.getElementById('crm-products').innerHTML = `<div class="toolbar"><h3 style="margin:0">Menu performance</h3><select id="crm-sort" class="input" style="width:auto"><option value="units">Most sold</option><option value="revenue">Highest revenue</option><option value="trend">Fastest growth</option><option value="decline">Biggest decline</option></select></div><div style="overflow:auto"><table style="width:100%;border-collapse:collapse;margin-top:12px"><thead><tr style="text-align:left;color:var(--muted)"><th>Product</th><th>Units</th><th>Revenue</th><th>Orders</th><th>Trend</th></tr></thead><tbody>${products.map(product => `<tr data-product="${esc(product.key)}" style="border-top:1px solid var(--line);cursor:pointer"><td style="padding:12px 4px;font-weight:700">${esc(product.name)}</td><td>${product.units}</td><td>${money(product.revenue)}</td><td>${product.orders}</td><td style="color:${product.trend >= 0 ? 'var(--g)' : 'var(--red)'}">${product.trend == null ? 'New' : `${product.trend >= 0 ? '+' : ''}${product.trend}%`}</td></tr>`).join('')}</tbody></table></div><div id="crm-product-detail" class="notice" style="margin-top:15px"></div>`;
        document.getElementById('crm-sort').addEventListener('change', renderProducts); document.querySelectorAll('[data-product]').forEach(row => row.addEventListener('click', () => { const product = products.find(item => item.key === row.dataset.product); document.getElementById('crm-product-detail').innerHTML = product ? `<div class="panel" style="margin-top:12px"><h3 style="margin-top:0">${esc(product.name)}</h3><p>${product.units} units sold, generating ${money(product.revenue)} across ${product.orders} orders.</p><p>Average quantity/order: ${product.averageQuantity.toFixed(1)} · Best days: ${esc(product.bestDays.join(', ') || 'Not enough data')} · Commonly bought with: ${esc(product.alongside.map(item => item.name).join(', ') || 'Not enough data')}</p><p>Frequent customers: ${esc(product.customers.join(', ') || 'Not enough data')}</p></div>` : ''; }));
    }
    function renderCustomers() {
        const filter = document.getElementById('crm-segment')?.value || ''; const customers = (data.customers || []).filter(customer => !filter || customer.segment === filter);
            document.getElementById('crm-customers').innerHTML = customers.length ? `<div class="customer-grid">${customers.map(customer => `<details class="item customer-card"><summary style="cursor:pointer"><strong>${esc(customer.name)}</strong><span class="notice">${esc(customer.segment)}</span></summary><div class="customer-facts"><div><b>Email</b><span>${esc(customer.email || '—')}</span></div><div><b>Phone</b><span>${esc(customer.phone || '—')}</span></div><div><b>Address</b><span>${esc(customer.address || '—')}</span></div><div><b>Spending</b><span>${money(customer.spent)} total · ${money(customer.averageOrderValue)} avg</span></div><div><b>Favourite items</b><span>${(customer.favoriteItems || []).map(item => `${item.name} (${item.quantity})`).join(', ') || '—'}</span></div><div><b>Order IDs</b><span>${(customer.orderIds || []).map(esc).join(', ') || '—'}</span></div><div><b>Order dates</b><span>${(customer.history || []).map(order => date(order.date)).join(', ') || '—'}</span></div></div><div class="customer-history">${customer.history.map(order => `<div><b>${esc(order.reference)}</b><span>${date(order.date)} · ${money(order.total)} · ${esc(order.status)} · ${esc(order.address)}</span><span>${order.items.map(item => `${item.quantity}× ${esc(item.name)}`).join(', ')}</span></div>`).join('')}</div><textarea class="input crm-notes" data-customer="${esc(customer.key)}" rows="2" placeholder="Customer notes">${esc(customer.notes)}</textarea><button class="btn secondary crm-save-note" data-customer="${esc(customer.key)}">Save note</button></details>`).join('')}</div>` : '<p class="notice">No customers match this filter yet.</p>';
        document.querySelectorAll('.crm-save-note').forEach(button => button.addEventListener('click', async () => { const notes = document.querySelector(`.crm-notes[data-customer="${CSS.escape(button.dataset.customer)}"]`).value; await request('/admin/customers/' + encodeURIComponent(button.dataset.customer) + '/notes', { method: 'PATCH', body: JSON.stringify({ notes }) }); button.textContent = 'Saved'; setTimeout(() => button.textContent = 'Save note', 1200); }));
    }
    function render() {
        const summary = data.summary || {}; const period = document.getElementById('crm-range')?.selectedOptions[0]?.textContent || 'Today'; const change = summary.salesChange == null ? 'No comparison yet' : `${summary.salesChange >= 0 ? '+' : ''}${summary.salesChange}% vs previous period`;
        document.getElementById('crm-summary').innerHTML = card(`Sales · ${period.toLowerCase()}`, money(summary.sales), change) + card('Orders', summary.orders) + card('Average order', money(summary.averageOrderValue)) + card('Items sold', summary.units) + card('Identified customers', summary.uniqueCustomers) + card('New customers', summary.newCustomers) + card('Returning customers', summary.returningCustomers);
        document.getElementById('crm-insights').innerHTML = data.insights?.length ? `<h3>What to pay attention to</h3><div class="alert">${data.insights.map(esc).join('<br>')}</div>` : '<p class="notice">More paid orders are needed before reliable insights can be shown.</p>';
        renderProducts(); renderCustomers();
    }
    async function load() { if (!sessionStorage.getItem('maychills_admin_token')) return; addPages(); try { const range = document.getElementById('crm-range')?.value || 'today'; const end = new Date(); let start = new Date(end.getFullYear(), end.getMonth(), end.getDate()); if (range === 'month') start = new Date(end.getFullYear(), end.getMonth(), 1); else if (range !== 'today') start.setDate(start.getDate() - Number(range) + 1); data = await request(`/admin/analytics?from=${start.toISOString().slice(0, 10)}&to=${end.toISOString().slice(0, 10)}`); render(); } catch (error) { const target = document.getElementById('crm-summary'); if (target) target.innerHTML = '<p class="notice" style="color:var(--red)">Analytics are unavailable. Check the database connection.</p>'; } }
    function enhanceOrderBoard() { const container = document.getElementById('orders'); if (!container || container.dataset.grouped === 'true') return; const cards = [...container.querySelectorAll(':scope > .order-card')]; if (!cards.length) return; cards.forEach(card => { const select = card.querySelector('[data-order-status]'); if (select && !select.querySelector('option[value="picked_up"]')) select.insertAdjacentHTML('beforeend', '<option value="picked_up">Picked up</option>'); }); const groups = [['New orders', ['received']], ['Processing', ['preparing']], ['Ready for collection', ['ready']], ['In transit', ['in_transit', 'out_for_delivery']], ['Completed', ['delivered', 'picked_up']], ['Historical', ['cancelled']]]; container.innerHTML = ''; groups.forEach(([title, statuses]) => { const matching = cards.filter(card => statuses.includes(card.querySelector('[data-order-status]')?.value || 'received')); if (!matching.length) return; const section = document.createElement('section'); section.className = 'order-status-section'; section.innerHTML = `<h3>${title} <span class="notice">(${matching.length})</span></h3>`; const grid = document.createElement('div'); grid.className = 'order-status-grid'; matching.forEach(card => grid.appendChild(card)); section.appendChild(grid); container.appendChild(section); }); container.dataset.grouped = 'true'; }
    const orderObserver = new MutationObserver(() => { const container = document.getElementById('orders'); if (container && container.querySelector(':scope > .order-card')) { container.dataset.grouped = ''; enhanceOrderBoard(); } });
    const watcher = setInterval(() => { if (document.getElementById('app') && !document.getElementById('app').classList.contains('hidden')) { clearInterval(watcher); load(); const container = document.getElementById('orders'); if (container) { orderObserver.observe(container, { childList: true }); enhanceOrderBoard(); } } }, 250);
})();
